// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eityrlacwydvjbgjxojl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpdHlybGFjd3lkdmpiZ2p4b2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzQzNzYsImV4cCI6MjA2MTI1MDM3Nn0.3Z5qxlirEMfx574OfN38P0WT78AyU2pCbj0XSmuTqrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);